// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs0TKlsd4kxahR1CmZB7wOTBqu6tXOdsA',
    appId: '1:404551935023:web:1085c7aebe6e329a5752da',
    messagingSenderId: '404551935023',
    projectId: 'coorditots',
    authDomain: 'coorditots.firebaseapp.com',
    databaseURL: 'https://coorditots-default-rtdb.firebaseio.com',
    storageBucket: 'coorditots.appspot.com',
    measurementId: 'G-FD324LFLK8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5DIA9kLHZxPY92fLEgHSbFxmk3a49Y4g',
    appId: '1:404551935023:android:72716edf2cde24775752da',
    messagingSenderId: '404551935023',
    projectId: 'coorditots',
    databaseURL: 'https://coorditots-default-rtdb.firebaseio.com',
    storageBucket: 'coorditots.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8hcM4yQjJkYEWBqlIHPQDc3bvZyt71vc',
    appId: '1:404551935023:ios:2c6a65fb4cf327815752da',
    messagingSenderId: '404551935023',
    projectId: 'coorditots',
    databaseURL: 'https://coorditots-default-rtdb.firebaseio.com',
    storageBucket: 'coorditots.appspot.com',
    iosClientId: '404551935023-jc2lvqbsfa3daogpusa1ghsgdh29ften.apps.googleusercontent.com',
    iosBundleId: 'com.benfallas.coorditots',
  );
}
